<?php include_once BASE_PATH . 'Vistas' . DS . 'Layout' . DS . 'Default' . DS . 'Navegacion.php'; ?>
<div class="panel panel-primary">
    <div class="panel-heading ui-jqgrid-titlebar ui-widget-header ui-corner-top ui-helper-clearfix">
        <h3 class="panel-title"><?php echo $this->titulo; ?></h3>
    </div>
    <div class="panel-body">
<table id="lista_cursos" class="table table-striped table-hover">
    <thead>
        <tr>
            <th></th>
            <th>Id</th>
            <th>Curso</th>
            <th>Observaciones</th>
        </tr>
    </thead>
    <tbody>
    <?php 
    foreach ($this->datos as $ciclo) { 
        echo '<tr id="' . $ciclo->getId() . '" name="' . $ciclo->getCurso() . '" >';
            echo '<td></td>';
            echo '<td>' . $ciclo->getId() . '</td>';?>
            <td>
                <?php echo $ciclo->getCurso(); ?>
            </td>
            <td>
                <?php echo $ciclo->getObservaciones(); ?>
            </td>
        </tr>
    <?php } ?>
        </tbody>
</table>
        </div>
</div>
<?php include_once 'Dlg_Eliminar.php'; ?>