<div class="panel panel-primary">
    <div class="panel-heading ui-jqgrid-titlebar ui-widget-header ui-corner-top ui-helper-clearfix">
        <h3 class="panel-title"><?php echo $this->titulo; ?></h3>
    </div>
    <div class="panel-body">
        <table id="listar_alumnos" class="table table-striped table-hover" curso="<?php echo $this->curso_id; ?>">
            <thead>
                <tr>
                    <th></th>
                    <th>Id</th>
                    <th>Apellido</th>
                    <th>Nombre</th>
                    <th>Documento</th>
                </tr>
            </thead>
            <tbody>
                <?php
                foreach ($this->datos as $alumno) {
                    echo '<tr id="' . $alumno->getId() . '" name="' . $alumno->getAyN() . '" >';
                    echo '<td></td>';
                    echo '<td>' . $alumno->getId() . '</td>';
                    ?>
                <td>
                    <?php echo $alumno->getApellidos(); ?>
                </td>
                <td>
                    <?php echo $alumno->getNombres(); ?>
                </td>
                <td>
                    <?php // echo $alumno->getTipo_Doc() . ' ' . $alumno->getNro_Doc(); ?>
                    <?php echo $alumno->getNro_Doc(); ?>
                </td>
                </tr>
            <?php } ?>
            </tbody>
        </table>
    </div>
</div>