<?php include_once BASE_PATH . 'Vistas' . DS . 'Layout' . DS . 'Default' . DS . 'Navegacion.php'; ?>
<div class="panel panel-primary">
    <div class="panel-heading ui-jqgrid-titlebar ui-widget-header ui-helper-clearfix">
        <h4>&nbsp;<span class="glyphicon glyphicon-user"></span> <?php echo $this->titulo; ?></h4>
    </div>
    <div class="panel-body" id="datos_usuario">
        <div class="row">
            <div class="col-sm-2"></div>
            <div class="col-sm-8">
                <?php include_once 'Forms' . DS . 'Form_EditarUsuario.php'; ?>
            </div>
            <div class="col-sm-2"></div>
        </div>
    </div>
</div>