<div class="row">

    <?php include_once 'Info.phtml'; ?>

    <div class="col-9">
        <nav class="navbar navbar-toggler-md">
            <?php if (isset($this->_barraHerramientas_principal) AND is_array($this->_barraHerramientas_principal)): ?>
                <div id="barraherramientas" class="container">
                    <div id="toolbar" class="toolbar">
                    </div>
                </div>
                <?php
            elseif (isset($this->_barraHerramientas_principal)):
                echo $this->_barraHerramientas_principal;
            endif;
            ?>
            <?php if (isset($this->_msj_error)): ?>
                <div id="mensaje" class="ui-state-error ui-corner-all" style="display: block;">
                    <?php
                    if (is_array($this->_msj_error)) {
                        foreach ($this->_msj_error as $error) {
                            echo $error;
                        }
                    } else {
                        echo $this->_msj_error;
                    }
                    ?></div>
            <?php endif; ?>
            <?php if (isset($this->_mensaje)) { ?>
                <div id="mensaje" class="ui-state-highlight ui-corner-all" style="display: block;">
                    <?php echo $this->_mensaje; ?>
                </div>
            <?php } ?>
        </nav>
    </div>
    <?php
    if (isset($this->estadisticas)) {
        include 'Estadisticas.phtml';
    }
    ?>
</div>
