<div class="col-3 col-sm-3 col-md-3 animated slideInLeft">
  <ul class="list-group">
      <li class="list-group-item active">
          <h6 class="w-100 text-center">
              <i class="fa fa-institution"></i>
              <?php echo INSTITUTO_NAME; ?>
          </h6>
          <h5 class="w-100 text-center">
              <span class="badge badge-pill badge-info">
                  <?php echo COD; ?>
              </span>
          </h5>
      </li>
      <li class="list-group-item">
          <h6 class="w-100">
              <i class="fa fa-flag"></i>
              <?php echo ' CUE'; ?>
          </h6>
          <h5>
              <span class="badge badge-pill badge-info"><?php echo CUE; ?></span>
          </h5>
      </li>
      <li class="list-group-item">
          <h6 class="w-100">
              <span class="fa fa-calendar" style="color:magenta"></span>
              <?php echo 'Ciclo actual'; ?>
          </h6>
          <h5>
              <span class="badge badge-pill badge-info">
                  <?php echo $this->ciclo; ?>
              </span>
          </h5>
      </li>
      <li class="list-group-item klanimate">
          <h6 class="w-100">
              <span class="fa fa-users"></span>
              <?php echo 'Alumnos en total'; ?>
          </h6>
          <h5>
              <span class="badge badge-pill badge-info">
                  <?php echo $this->alumnos; ?>
              </span>
          </h5>
      </li>
      <li class="list-group-item">
          <h6 class="w-100">
              <span class="fa fa-briefcase" style="color:blue"></span>
              <?php echo 'Personal '; ?>
          </h6>
          <h5>
              <span class="badge badge-pill badge-info"><?php echo $this->personal; ?></span>
          </h5>
      </li>
      <li class="list-group-item">
          <h6 class="w-100">
              <span class="fa fa-user-o" style="color:red"></span>
                      <?php echo 'Usuarios en el Sistema'; ?>
          </h6>
          <h5>
              <span class="badge badge-pill badge-info">
                  <?php echo $this->usuarios; ?>
              </span>
          </h5>
      </li>
      <li class="list-group-item">
          <h6 class="w-100">
              <span class="fa fa-building-o" style="color:green"></span>
              <?php echo 'Cursos'; ?>
          </h6>
          <h5>
              <span class="badge badge-pill badge-info">
                  <?php echo $this->cursos; ?>
              </span>
          </h5>
      </li>
  </ul>
</div>
