<?php include_once BASE_PATH . 'Vistas' . DS . 'Layout' . DS . 'Default' . DS . 'Navegacion.php'; ?>
<div class="panel panel-primary">
    <div class="panel-heading ui-jqgrid-titlebar ui-widget-header ui-corner-top ui-helper-clearfix">
        <h3 class="panel-title"><?php echo $this->titulo; ?></h3>
    </div>
    <div class="panel-body">
        <table id="lista_roles" class="table table-striped table-hover">
    <thead>
        <tr>
            <th></th>
            <th>Id</th>
            <th>Role</th>
        </tr>
    </thead>
    <tbody>
        <?php 
        foreach ($this->datos as $rol) { 
        echo '<tr id="' . $rol['id_role'] . '" role="' . $rol['role'] . '" >';?>
            <td>
                
            </td>
            <?php echo '<td>' . $rol['id_role'] . '</td>';?>
            <td>
                <?php echo $rol['role']; ?>
            </td>          
        </tr>
    <?php } ?>

    </tbody>
    </table>
        
    </div>
</div>
