<div class="col-md-12 ui-corner-all">
    <form id="editar_lista" method="post" action="" class="form-horizontal" role="form">
        <input type="hidden" name="editarLista" value="1" />
        <input type="hidden" name="ciclo_lectivo" value="<?php echo $this->cicloActual->getCiclo(); ?>" />
        <input type="hidden" name="id" id="id"
               value="<?php echo $this->cicloActual->getId(); ?>" />        
        <div class="col-md-6 ui-corner-all">
            <div class="form-group">
                <label for="alumnos">Cursos Disponibles:</label>
                <select multiple class="form-control" id="cursos_disponibles" size="10">
                    <?php
                    foreach ($this->cursos as $curso) {
                        echo '<option value="' . $curso->getId() .'">' . $curso->getCurso() . '</option>';
                    }
                    ?>
                </select>
                <p class="help-block"><?php echo count($this->cursos) . ' cursos disponibles'; ?></p>
            </div>
            <div class="form-group">
                <button type="button" class="btn btn-primary" id="btn_agregar">Agregar</button>
            </div>
        </div>
        <div class="col-md-6 ui-corner-all">
            <div class="form-group">
                <label for="inscriptos">Cursos en el Ciclo:</label>
                <select multiple class="form-control" id="cursos_activos" size="10">
                    <?php
                    foreach ($this->cursosEnCiclo as $curso) {
                        echo '<option value="' . $curso->getId() .'">' . $curso->getCurso() . '</option>';
                    }
                    ?>
                </select>
                <p class="help-block"><?php echo count($this->cursosEnCiclo) . ' cursos en este ciclo'; ?></p>
            </div>

            <div class="form-group">
                <button type="button" class="btn btn-danger" id="btn_quitarCurso">Quitar</button>
            </div>
        </div>

    </form>
</div>