<?php include_once BASE_PATH . 'Vistas' . DS . 'Layout' . DS . 'Default' . DS . 'Navegacion.php'; ?>
<div class="panel panel-primary">
    <div class="panel-heading ui-jqgrid-titlebar ui-widget-header ui-corner-top ui-helper-clearfix">
        <h3 class="panel-title"><?php echo $this->titulo; ?></h3>
    </div>
    <div class="panel-body">
<table id="lista_ciclos" class="table table-striped table-hover">
    <thead>
        <tr>
            <th></th>
            <th>Id</th>
            <th>Ciclo</th>
            <th>Actual</th>
            <th>Observaciones</th>
        </tr>
    </thead>
    <tbody>
    <?php 
    foreach ($this->datos as $ciclo) { 
        if ($ciclo->getActual()==1){
            echo '<tr id="' . $ciclo->getId() . '" name="' . $ciclo->getCiclo() . '" class="info">';
        }else{
            echo '<tr id="' . $ciclo->getId() . '" name="' . $ciclo->getCiclo() . '" >';
        }
            echo '<td></td>';
            echo '<td>' . $ciclo->getId() . '</td>';?>
            <td>
                <?php echo $ciclo->getCiclo(); ?>
            </td>
            <td>
                <?php
                if ($ciclo->getActual()==1){
                    echo '<span class="glyphicon glyphicon-star"></span>'; 
                }else{
                    echo '<a href="javascript:void(0);" idCiclo="'. $ciclo->getId() .
                            '" onclick="javascript: setCicloActual()" id="setCicloActual">';
                    echo '<span class="glyphicon glyphicon-star-empty"></span>'; 
                    echo '</a>';
                }
                ?>
            </td>
            <td>
                <?php echo $ciclo->getObservaciones(); ?>
            </td>
        </tr>
    <?php } ?>
        </tbody>
</table>
        </div>
</div>
<?php include_once 'Dlg_Eliminar.php'; ?>