<?php include_once BASE_PATH . 'Vistas' . DS . 'Layout' . DS . 'Default' . DS . 'Navegacion.php'; ?>

<div class="panel panel-primary">
    <div class="panel-heading ui-jqgrid-titlebar ui-widget-header ui-corner-top ui-helper-clearfix">
        <h3 class="panel-title"><?php echo $this->titulo; ?></h3>
    </div>

    <p>De acuerdo con los servicios prestados, las principales áreas de 
        intervención del Instituto en este momento están relacionadas con:</p>
    <table id="lista_areas" class="table table-striped table-hover">
        <thead>
            <tr>
                <th></th>
                <th>Área</th>
            </tr>
        </thead>
        <tbody>
            <?php
            foreach ($this->listaPuestos as $puesto) {
                echo '<tr id="' . $puesto->getId() . '" >';
                ?>
            <td>

            </td>
            <td>
                <?php echo $puesto->getPuesto(); ?>
            </td>          
            </tr>
        <?php } ?>
        </tbody>
    </table>
</div>
