<?php include_once BASE_PATH . 'Vistas' . DS . 'Layout' . DS . 'Default' . DS . 'Navegacion.php'; ?>

<div class="panel panel-primary">
    <div class="panel-heading ui-jqgrid-titlebar ui-widget-header ui-corner-top ui-helper-clearfix">
        <h3 class="panel-title"><?php echo $this->titulo; ?></h3>
    </div>
    <div class="panel-body">
        <table id="lista_iva" class="table table-striped table-hover">
            <thead>
                <tr>
                    <th></th>
                    <th class="text-center">Id</th>
                    <th>Contribuyente</th>
                </tr>
            </thead>
            <tbody>
                <?php
                foreach ($this->listaIva as $iva) {
                    echo '<tr id="' . $iva->getId() . '" name="' . $iva->getContribuyente() . '" >';
                    ?>
                <td></td>
                <td class="hidden-xs text-center">
                    <?php echo $iva->getId(); ?>
                </td>
                <td>
                    <?php echo $iva->getContribuyente(); ?>
                </td>
                </tr>
            <?php } ?>

            </tbody>
        </table>
    </div>
</div>
<?php include_once 'Dlg_EliminarIva.php'; ?>