<?php include_once BASE_PATH . 'Vistas' . DS . 'Layout' . DS . 'Default' . DS . 'Navegacion.php'; ?>

<div class="panel panel-primary">
    <div class="panel-heading ui-jqgrid-titlebar ui-widget-header ui-corner-top ui-helper-clearfix">
        <h3 class="panel-title"><?php echo $this->titulo; ?></h3>
    </div>
    <div class="panel-body">
        <table id="lista_modulos" class="table table-striped table-hover">
            <thead>
                <tr>
                    <th></th>
                    <th>Módulo</th>
                    <th>Habilitado</th>
                    <th>Tipo</th>
                    <th>Visible</th>
                </tr>
            </thead>
            <tbody>
                <?php
                foreach ($this->listaModulos as $modulo) {
                    echo '<tr id="' . $modulo->getId() . '" name="' . $modulo->getModulo() . '" >';
                    ?>
                <td>
                </td>
                <td>
                    <?php echo $modulo->getModulo(); ?>
                </td>          
                <td>
                    <?php echo $modulo->getHabilitado(); ?>
                </td>          
                <td>
                    <?php echo $modulo->getTipo(); ?>
                </td>          
                <td>
                    <?php echo $modulo->getVisible(); ?>
                </td>          
                </tr>
            <?php } ?>
            </tbody>
        </table>

    </div>
</div>
<?php include_once 'Dlg_Eliminar.php'; ?>