<?php include_once BASE_PATH . 'Vistas' . DS . 'Layout' . DS . 'Default' . DS . 'Navegacion.php'; ?>

<div class="panel panel-primary">
    <div class="panel-heading ui-jqgrid-titlebar ui-widget-header ui-corner-top ui-helper-clearfix">
        <h3 class="panel-title"><?php echo $this->titulo; ?></h3>
    </div>
    <div class="panel-body">
        <table id="lista_puestos" class="table table-striped table-hover">
            <thead>
                <tr>
                    <th></th>
                    <th>Id</th>
                    <th>Puesto</th>
                </tr>
            </thead>
            <tbody>
                <?php
                foreach ($this->listaPuestos as $puesto) {
                    echo '<tr id="' . $puesto->getId() . '" name="' . $puesto->getPuesto() . '" >';
                    ?>
                <td>
                </td>
                <td>
                    <?php echo $puesto->getId(); ?>
                </td>          
                <td>
                    <?php echo $puesto->getPuesto(); ?>
                </td>          
                </tr>
            <?php } ?>
            </tbody>
        </table>

    </div>
</div>
<?php include_once 'Dlg_Eliminar.php'; ?>