<div class="col-md-7 ui-corner-all">
    <form id="editar_paciente" method="post" action="" class="form-horizontal" role="form">
        <input type="hidden" name="editar" value="1" />
        <input type="hidden" name="id" id="id"
               value="<?php echo $this->datos->getId(); ?>" />
        <div class="form-group">
            <label for="estado" class="required col-sm-2 control-label">Estado:</label>
            <div class="col-sm-10">
                <select name="estado" id="estado" class="form-control">
                    <?php
                    foreach ($this->estadosAlumno as $estado) {
                        if ($this->datos->getEstado() == $estado) {
                            $seleccionado = ' selected="selected" ';
                        } else {
                            $seleccionado = '';
                        }
                        echo "<option value=\"$estado\" label=\"$estado\" $seleccionado>$estado</option>";
                    }
                    ?>
                </select>
            </div>
        </div>
        <?php require_once BASE_PATH . 'LibQ' . DS . 'Html'. DS . 'Form_Element'. DS .'Input_Apellidos.php';
        $apellidos = new LibQ_Html_Form_Element_Input_Apellidos($this->datos->getApellidos());
        $apellidos->render();
        ?>
        <?php require_once BASE_PATH . 'LibQ' . DS . 'Html'. DS . 'Form_Element'. DS .'Input_Nombres.php';
        $nombres = new LibQ_Html_Form_Element_Input_Nombres($this->datos->getNombres());
        $nombres->render();
        ?>
        <div class="form-group">
            <label for="tipo_doc" class="optional col-sm-2 control-label">Tipo Doc:</label>
            <div class="col-sm-10">
                <select name="tipo_doc" id="tipo_doc" class="form-control">
                    <option value="0" label="DNI" selected="selected">DNI</option>
                    <option value="1" label="CI">CI</option>
                </select>
            </div>
        </div>
        <?php require_once BASE_PATH . 'LibQ' . DS . 'Html'. DS . 'Form_Element'. DS .'Input_Nro_Doc.php';
        $nro_doc = new LibQ_Html_Form_Element_Input_Nro_Doc($this->datos->getNro_doc());
        $nro_doc->render();
        ?>
        <div class="form-group">
            <label for="cuil" class="col-sm-2 control-label">CUIL:</label>
            <div class="col-sm-10">
                <input type="text" name="cuil" id="cuil"
                       value="<?php if ($this->datos->getCuil()) echo $this->datos->getCuil(); ?>" 
                       class="form-control">
            </div>
        </div>
        
        <?php require_once BASE_PATH . 'LibQ' . DS . 'Html'. DS . 'Form_Element'. DS .'Input_Autocomplete_Nacionalidad.php';
        $nacionalidad = new LibQ_Html_Form_Element_Input_Autocomplete_Nacionalidad($this->datos->getNacionalidad(), $this->listaNacionalidades);
        $nacionalidad->render();
        ?>
        <?php require_once BASE_PATH . 'LibQ' . DS . 'Html'. DS . 'Form_Element'. DS .'Select_Sexo.php';
        $sexo = new LibQ_Html_Form_Element_Select_Sexo($this->datos->getSexo(), $this->listaSexos);
        $sexo->render();
        ?>
        
        <div class="form-group">
            <label for="fechaNac" class="required col-sm-2 control-label">Fecha Nac.:</label>
            <div class="col-sm-10">
                <?php echo '<input type="date" name="fechaNac" id="fechaNac" 
                            value="' . $this->datos->getFecha_nac() . '"  
                                class="form-control">'; ?>
            </div>
        </div>
        <div class="form-group">
            <input type="submit" class="btn btn-lg btn-primary btn-block" name="boton_guardar" value="Guardar">
        </div>
    </form>
</div>