<?php include_once BASE_PATH . 'Vistas' . DS . 'Layout' . DS . 'Default' . DS . 'Navegacion.php'; ?>

<div class="panel panel-primary">
    <div class="panel-heading ui-jqgrid-titlebar ui-widget-header ui-helper-clearfix">
        <h3 class="panel-title"><?php echo $this->titulo; ?></h3>
    </div>
    <div id = "tabs">
        <ul>
            <li><a href="#tabs-1">Datos Principales</a></li>
            <li><a href="#tabs-2">Domicilio</a></li>
            <li><a href="#tabs-3">Contactos</a></li>
            <li><a href="#tabs-4">Familia</a></li>
            <?php if (isset($this->datosSalud)) { ?>
                <li><a href="#tabs-5">Salud</a></li>
            <?php } ?>
            <?php if (isset($this->datosTerapia)) { ?>
                <li><a href="#tabs-6">Terapias</a></li>
            <?php } ?>
            <?php if (isset($this->datosOSocial)) { ?>
                <li><a href="#tabs-7">Obra Social</a></li>
            <?php } ?>
            <?php if (isset($this->datosEducacion)) { ?>
                <li><a href="#tabs-8">Educación</a></li>
            <?php } ?>
            <?php if (isset($this->datosFoto)) { ?>
                <li><a href="#tabs-9">Foto</a></li>
            <?php } ?>

        </ul>
        <div id = "tabs-1">
            <div class="row">
                <?php include_once 'Forms/Form_Editar.phtml'; ?>
                <?php include_once 'Forms/Form_FotosAlumno.php'; ?>
            </div>
        </div>
        <div id = "tabs-2"><?php include_once 'DatosDomicilio.php'; ?></div>
        <div id = "tabs-3"><?php include_once 'DatosContacto.php'; ?></div>
        <div id = "tabs-4"><?php include_once 'DatosFamilia.php'; ?></div>
        <?php if (isset($this->datosSalud)) { ?>
            <div id = "tabs-5"><?php include_once 'DatosSalud.php'; ?></div>
        <?php } ?>
        <?php if (isset($this->datosTerapia)) { ?>
            <div id = "tabs-6"><?php include_once 'DatosTerapia.php'; ?></div>
        <?php } ?>
        <?php if (isset($this->datosOSocial)) { ?>
            <div id = "tabs-7"><?php include_once 'DatosOSocial.php'; ?></div>
        <?php } ?>
        <?php if (isset($this->datosEducacion)) { ?>
            <div id = "tabs-8"><?php include_once 'DatosEducacion.php'; ?></div>
        <?php } ?>
        <?php if (isset($this->datosFoto)) { ?>
            <div id = "tabs-9"><?php include_once 'FotoPaciente.php'; ?></div>
        <?php } ?>
    </div>