<div class="row">
  <?php if( isset($this->info) ) {?>
  <div class="col-3">
      <?php 
        include_once MODS_PATH . 'BloqueInfo' . DS . 'Vistas' . DS . 'index.phtml'; 
      ?>
  </div>
  <div class="col-9">
  <?php } else { ?>
  <div class="col-12">
  <?php }  ?>    
      <?php include_once BASE_PATH . 'Vistas' . DS . 'Layout' . DS . 'Default' . DS . 'Navegacion.php'; ?>
      <?php include_once 'Lista.phtml'; ?>
  </div>
  <?php include_once 'Dlg_Eliminar.php'; ?>
</div>
