<form id="ciclo" method="post" action="index.php?mod=Ciclo&cont=index&met=nuevo" class="form-horizontal" role="form">
    <div class="col-md-7 ui-corner-all">
        <input type="hidden" name="guardar" value="1" />
        <div class="form-group">
            <label for="ciclo" class="required col-sm-2 control-label">Ciclo:</label>
            <div class="col-sm-10">
                <input type="text" name="ciclo" id="ciclo"
                       value="" maxlength="4" size="4" 
                       class="form-control" required
                       data-bv-notempty-message="El Ciclo es obligatorio">
            </div>
        </div>
        <div class="form-group">
            <label for="observaciones" class="required col-sm-2 control-label">Observaciones:</label>
            <div class="col-sm-10">
                <input type="text" name="observaciones" id="observaciones" 
                       value="" maxlength="250" size="25" 
                       class="form-control">
            </div>
        </div>
    </div>
    <input type="submit" class="btn btn-lg btn-primary btn-block" name="boton_guardar" value="Guardar">
</form>