<div class="list-group">
    <div class="list-group-item active">
        <h4 class="list-group-item-heading">
            Estadísticas
        </h4>
    </div>

    <div class="list-group-item">
        <h4 class="list-group-item-heading">
            <span class="fa fa-group"></span>
            TOTAL:
        </h4>
        <p class="list-group-item-text">
            <?php echo count($this->datos) . ' personas  en la Base de Datos'; ?>
        </p>
    </div>
    <div class="list-group-item">
        <h4 class="list-group-item-heading">
            <span class="fa fa-male" style="color:blue"></span>
            VARONES:
        </h4>
        <p class="list-group-item-text">
            <?php echo count($this->varones) . ' Varones en la Base de Datos'; ?>
        </p>
    </div>
    <div class="list-group-item">
        <h4 class="list-group-item-heading">
            <span class="fa fa-female" style="color:red"></span>
            MUJERES:
        </h4>
        <p class="list-group-item-text">
            <?php echo count($this->mujeres) . ' Mujeres en la Base de Datos'; ?>
        </p>
    </div>
</div>